version: '3.6'

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  geoipapi:
    image: 
      workivate/geoip-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"