FROM python:3.7-alpine

LABEL lifeworks.codetest.version="0.0.1-beta"

COPY . /usr/src/app/

RUN apk add --update py3-pip

RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt

EXPOSE 5000

CMD ["python", "/usr/src/app/app.py"]

